import type { UserManagerSettings } from 'oidc-client-ts';
import { UserManager, WebStorageStateStore } from 'oidc-client-ts';

// OIDC wiring (ADR-0029). Every value is generated by ResourcePulse.DevBootstrap
// into .env.local; nothing here is hard-coded, and nothing is a secret — a SPA
// is a public client and holds no client secret by design.

const authority = import.meta.env.VITE_OIDC_AUTHORITY;
const clientId = import.meta.env.VITE_OIDC_CLIENT_ID;

/**
 * Whether an identity provider is configured at all. When it is not, the app
 * runs against the API's FakeAuth scheme — the default local dev loop — and the
 * auth provider degrades to a pass-through instead of redirecting nowhere.
 */
export const isOidcConfigured = Boolean(authority && clientId);

/**
 * Zitadel ignores a bare `audience` parameter: the API's audience is requested
 * through this reserved scope, which puts the project id into the token's `aud`.
 * Without it the API rejects every token as having the wrong audience.
 */
const projectScope = import.meta.env.VITE_OIDC_PROJECT_SCOPE;

/**
 * Asks Zitadel to put the user's organization into the token.
 *
 * Without it the access token carries NO organization claim, tenant resolution
 * fails, and every authenticated request is refused with 403 — including
 * `GET /api/me`, which is exempt from the membership requirement but not from
 * tenant resolution (ADR-0029/0030). The failure looks like "you have no access"
 * and is really "we could not tell which tenant you belong to".
 *
 * `urn:zitadel:iam:org:id:{id}` would be the other reserved scope, but that one
 * *pins* a specific organization rather than reporting the user's own.
 */
const RESOURCE_OWNER_SCOPE = 'urn:zitadel:iam:user:resourceowner';

export const oidcConfig: UserManagerSettings = {
  authority: authority ?? '',
  client_id: clientId ?? '',
  redirect_uri: import.meta.env.VITE_OIDC_REDIRECT_URI ?? `${window.location.origin}/auth/callback`,
  silent_redirect_uri:
    import.meta.env.VITE_OIDC_SILENT_REDIRECT_URI ?? `${window.location.origin}/auth/silent-renew`,
  post_logout_redirect_uri:
    import.meta.env.VITE_OIDC_POST_LOGOUT_REDIRECT_URI ?? window.location.origin,

  // Authorization Code + PKCE. `response_type: code` with a public client is
  // what makes PKCE the protection; there is no implicit flow anywhere here.
  response_type: 'code',
  scope: ['openid', 'profile', 'email', 'offline_access', RESOURCE_OWNER_SCOPE, projectScope]
    .filter(Boolean)
    .join(' '),

  // Renew ahead of expiry in a hidden iframe so an active user is never bounced
  // to the login page mid-session.
  automaticSilentRenew: true,
  // Tokens live in sessionStorage: they die with the tab, which is a meaningful
  // improvement over localStorage for a browser-held credential. The real
  // hardening is a BFF — see ADR-0029, marked as a revisable default.
  userStore: new WebStorageStateStore({ store: window.sessionStorage }),
};

/** Where the user was headed before being sent off to log in. */
export type SigninState = { returnTo?: string };

/**
 * Starts an authorization request without going through the React auth context.
 *
 * The sign-in page runs OUTSIDE the provider (ADR-0031) — mounting the gate there
 * would have it redirect to the identity provider, which redirects back to the
 * sign-in page, forever. It still needs to be able to ask for an authorization
 * request when it was opened without one, so it drives a `UserManager` built from
 * the same settings: same client, same PKCE state store, same `returnTo` shape as
 * `AuthProvider`.
 */
export function startSignInRedirect(returnTo: string): void {
  void new UserManager(oidcConfig).signinRedirect({
    state: { returnTo } satisfies SigninState,
  });
}
