using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authorization.Policy;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ResourcePulse.Common.Auth;
using ResourcePulse.Common.Tenancy;
using ResourcePulse.Hosting;
using ResourcePulse.Hosting.Auth;
using ResourcePulse.Hosting.Setup;
using ResourcePulse.Http;
using ResourcePulse.Persistence.Tenancy;
using Serilog;

// The startup sequence, and as little else as possible. Each AddResourcePulse*
// owns one concern and explains itself in its own file (Auth/ and Setup/); what
// belongs HERE is the order, because in several places the order IS the
// correctness — see the middleware pipeline at the bottom.

var builder = WebApplication.CreateBuilder(args);

builder.Host.UseSerilog((ctx, cfg) =>
    cfg.ReadFrom.Configuration(ctx.Configuration));

builder.AddServiceDefaults();

// ProblemDetails + global exception handler
builder.Services.AddProblemDetails();
builder.Services.AddExceptionHandler<GlobalExceptionHandler>();

// Identity configuration generated by ResourcePulse.DevBootstrap (ADR-0029):
// issuer, project id and client ids. Optional so the app still starts on the
// FakeAuth path with no identity container running.
if (builder.Environment.IsDevelopment())
    builder.Configuration.AddJsonFile("zitadel-dev.json", optional: true, reloadOnChange: false);

// ── Identity and access ─────────────────────────────────────────────────────

// Auth — provider selected by Auth:Provider (Fake | Zitadel). Fake is the
// Development default so the zero-friction dev loop is unchanged.
builder.AddResourcePulseAuthentication();

// Application roles (ADR-0030): three hierarchical policies backed by OUR
// membership store. Registers ICurrentAccess and the requirement handler.
builder.AddResourcePulseAuthorization();

// Gives a failed role policy a ProblemDetails body with a distinct `type`, so the
// client can tell "not a member of this tenant" from "insufficient role".
builder.Services.AddSingleton<IAuthorizationMiddlewareResultHandler, AccessDeniedResultHandler>();

// Our own login page (ADR-0031). The typed client carries the login client's
// personal access token, which can finalise an authorization request for ANY
// user — so it lives here, in the API, and never in the browser.
builder.AddResourcePulseForwardedHeaders();
builder.AddResourcePulseLoginClient();

// ── Ambient request state ───────────────────────────────────────────────────

builder.Services.AddHttpContextAccessor();
// One clock for the whole process: the audit stamps, the detector, the plan
// envelope and the skill-approval workflow all read it, so "now" cannot mean
// two different things depending on which layer asked.
builder.Services.TryAddSingleton(TimeProvider.System);
// Singleton required: Aspire's AddNpgsqlDbContext uses AddDbContextPool.
// Pooled DbContexts are resolved from the root provider, so constructor-injected
// dependencies must be singletons. HttpContextCurrentUserAccessor reads
// IHttpContextAccessor.HttpContext at call time, so singleton lifetime is safe.
builder.Services.AddSingleton<ICurrentUserAccessor, HttpContextCurrentUserAccessor>();
// Same lifetime argument as above: the pooled DbContext's interceptors depend on
// it, so it must be a singleton that resolves the ambient request at call time.
builder.Services.AddSingleton<ITenantContext, HttpContextTenantContext>();

// ── The application ─────────────────────────────────────────────────────────

builder.AddResourcePulsePersistence();
builder.AddResourcePulseApplicationServices();

// MVC + global validation filter
builder.Services
    .AddControllers(opts => opts.Filters.Add<DtoValidationFilter>())
    // [DevelopmentOnly] controllers are removed from the application parts outside
    // Development: the route then does not exist, rather than existing and saying no.
    .ConfigureApplicationPartManager(apm => apm.FeatureProviders.Add(
        new DevelopmentOnlyControllerFeatureProvider(builder.Environment.IsDevelopment())));

builder.AddResourcePulseSwagger();

var app = builder.Build();

await app.RunResourcePulseDevBootstrapAsync();

// ── The pipeline, where order is correctness ────────────────────────────────

// FIRST, before anything reads the client address — the request logger and the
// login throttle both do. Off unless configured (review finding 6).
app.UseResourcePulseForwardedHeaders();

app.UseExceptionHandler();

app.UseResourcePulseSwagger();

// Serilog request logging enriched with current user Sub
app.UseSerilogRequestLogging(opts =>
{
    opts.EnrichDiagnosticContext = (diagnosticContext, httpContext) =>
    {
        var userAccessor = httpContext.RequestServices.GetService<ICurrentUserAccessor>();
        if (userAccessor?.IsAuthenticated == true)
            diagnosticContext.Set("UserSub", userAccessor.User.Sub);
    };
});

// Throttles the anonymous sign-in endpoints (ADR-0031). Deliberately BEFORE
// authentication: the endpoints it guards have no principal, and the point is to
// spend as little as possible on a caller who is spraying passwords.
app.UseRateLimiter();

app.UseAuthentication();
// After authentication (it reads the validated principal), before authorization
// and before any handler touches the tenant-scoped store.
app.UseTenantResolution();
// After the tenant (the membership table is tenant-scoped and RLS-protected —
// resolving access first would make everyone a non-member), before authorization.
app.UseAccessResolution();
app.UseAuthorization();

app.MapControllers();
app.MapDefaultEndpoints();

app.Run();
