// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResourcePulse.Persistence;

#nullable disable

namespace ResourcePulse.Persistence.Migrations
{
    [DbContext(typeof(ResourcePulseDbContext))]
    [Migration("20260519173801_WidenAllocationPercentBound")]
    partial class WidenAllocationPercentBound
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResourcePulse.Domain.Allocations.Allocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AllocationPercent")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("allocation_percent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<Guid>("ProjectNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_node_id");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_allocations");

                    b.HasIndex("ProjectNodeId", "PeriodStart", "PeriodEnd")
                        .HasDatabaseName("ix_allocations_project_node_id_period");

                    b.HasIndex("ResourceId", "PeriodStart", "PeriodEnd")
                        .HasDatabaseName("ix_allocations_resource_id_period");

                    b.ToTable("allocations", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Calendars.BusinessCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_business_calendars");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ix_business_calendars_is_default_unique")
                        .HasFilter("is_default = TRUE");

                    b.ToTable("business_calendars", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Calendars.CompanyClosure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_company_closures");

                    b.HasIndex("DateFrom", "DateTo")
                        .HasDatabaseName("ix_company_closures_date_from_date_to");

                    b.ToTable("company_closures", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Projects.ProjectNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActualEnd")
                        .HasColumnType("date")
                        .HasColumnName("actual_end");

                    b.Property<DateOnly?>("ActualStart")
                        .HasColumnType("date")
                        .HasColumnName("actual_start");

                    b.Property<DateOnly?>("BaselineEnd")
                        .HasColumnType("date")
                        .HasColumnName("baseline_end");

                    b.Property<DateOnly?>("BaselineStart")
                        .HasColumnType("date")
                        .HasColumnName("baseline_start");

                    b.Property<DateTimeOffset?>("BaselinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("baselined_at");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("CommitmentLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("commitment_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<TimeSpan?>("EstimatedWork")
                        .HasColumnType("interval")
                        .HasColumnName("estimated_work");

                    b.Property<Guid?>("LeadResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_resource_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("node_type");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("path");

                    b.Property<DateOnly?>("PlannedEnd")
                        .HasColumnType("date")
                        .HasColumnName("planned_end");

                    b.Property<DateOnly?>("PlannedStart")
                        .HasColumnType("date")
                        .HasColumnName("planned_start");

                    b.Property<string>("PlanningMode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("planning_mode");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_project_nodes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_project_nodes_root_code")
                        .HasFilter("parent_id IS NULL AND code IS NOT NULL");

                    b.HasIndex("LeadResourceId")
                        .HasDatabaseName("ix_project_nodes_lead_resource_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_project_nodes_parent_id");

                    b.HasIndex("Path")
                        .HasDatabaseName("ix_project_nodes_path");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Path"), new[] { "text_pattern_ops" });

                    b.HasIndex("NodeType", "Status")
                        .HasDatabaseName("ix_project_nodes_node_type_status");

                    b.HasIndex("ParentId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_project_nodes_parent_code")
                        .HasFilter("parent_id IS NOT NULL AND code IS NOT NULL");

                    b.ToTable("project_nodes", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Resources.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_calendar_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_resources");

                    b.HasIndex("BusinessCalendarId")
                        .HasDatabaseName("ix_resources_business_calendar_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_resources_team_id");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Skills.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_skills_name");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_teams_name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Allocations.Allocation", b =>
                {
                    b.HasOne("ResourcePulse.Domain.Projects.ProjectNode", null)
                        .WithMany()
                        .HasForeignKey("ProjectNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_allocations_project_nodes_project_node_id");

                    b.HasOne("ResourcePulse.Domain.Resources.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_allocations_resources_resource_id");
                });

            modelBuilder.Entity("ResourcePulse.Domain.Calendars.BusinessCalendar", b =>
                {
                    b.OwnsMany("ResourcePulse.Domain.Calendars.WorkWindow", "WorkWindows", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("BusinessCalendarId")
                                .HasColumnType("uuid")
                                .HasColumnName("business_calendar_id");

                            b1.Property<int>("DayOfWeek")
                                .HasColumnType("integer")
                                .HasColumnName("day_of_week");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("end_time");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("start_time");

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");

                            b1.HasKey("Id");

                            b1.HasIndex("BusinessCalendarId", "ValidFrom", "ValidTo")
                                .HasDatabaseName("ix_business_calendar_work_windows_business_calendar_id_valid_f");

                            b1.ToTable("business_calendar_work_windows", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BusinessCalendarId")
                                .HasConstraintName("fk_business_calendar_work_windows_business_calendars_business_");
                        });

                    b.Navigation("WorkWindows");
                });

            modelBuilder.Entity("ResourcePulse.Domain.Projects.ProjectNode", b =>
                {
                    b.HasOne("ResourcePulse.Domain.Resources.Resource", null)
                        .WithMany()
                        .HasForeignKey("LeadResourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_project_nodes_resources_lead_resource_id");

                    b.HasOne("ResourcePulse.Domain.Projects.ProjectNode", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_project_nodes_project_nodes_parent_id");

                    b.OwnsMany("ResourcePulse.Domain.Projects.ProjectNodeTag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("ProjectNodeId")
                                .HasColumnType("uuid")
                                .HasColumnName("project_node_id");

                            b1.Property<Guid>("TagId")
                                .HasColumnType("uuid")
                                .HasColumnName("tag_id");

                            b1.HasKey("ProjectNodeId", "TagId")
                                .HasName("pk_project_node_tags");

                            b1.HasIndex("TagId")
                                .HasDatabaseName("ix_project_node_tags_tag_id");

                            b1.ToTable("project_node_tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProjectNodeId")
                                .HasConstraintName("fk_project_node_tags_project_nodes_project_node_id");

                            b1.HasOne("ResourcePulse.Domain.Tags.Tag", null)
                                .WithMany()
                                .HasForeignKey("TagId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_project_node_tags_tags_tag_id");
                        });

                    b.OwnsMany("ResourcePulse.Domain.Projects.ProjectSkillRequirement", "SkillRequirements", b1 =>
                        {
                            b1.Property<Guid>("ProjectNodeId")
                                .HasColumnType("uuid")
                                .HasColumnName("project_node_id");

                            b1.Property<Guid>("SkillId")
                                .HasColumnType("uuid")
                                .HasColumnName("skill_id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("created_by");

                            b1.Property<string>("MinLevel")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("min_level");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("updated_by");

                            b1.HasKey("ProjectNodeId", "SkillId")
                                .HasName("pk_project_skill_requirements");

                            b1.HasIndex("SkillId")
                                .HasDatabaseName("ix_project_skill_requirements_skill_id");

                            b1.ToTable("project_skill_requirements", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProjectNodeId")
                                .HasConstraintName("fk_project_skill_requirements_project_nodes_project_node_id");

                            b1.HasOne("ResourcePulse.Domain.Skills.Skill", null)
                                .WithMany()
                                .HasForeignKey("SkillId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("fk_project_skill_requirements_skills_skill_id");
                        });

                    b.Navigation("SkillRequirements");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ResourcePulse.Domain.Resources.Resource", b =>
                {
                    b.HasOne("ResourcePulse.Domain.Calendars.BusinessCalendar", null)
                        .WithMany()
                        .HasForeignKey("BusinessCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resources_business_calendars_business_calendar_id");

                    b.HasOne("ResourcePulse.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_resources_teams_team_id");

                    b.OwnsMany("ResourcePulse.Domain.Resources.IndividualAdjustment", "Adjustments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("DateFrom")
                                .HasColumnType("date")
                                .HasColumnName("date_from");

                            b1.Property<DateOnly>("DateTo")
                                .HasColumnType("date")
                                .HasColumnName("date_to");

                            b1.Property<TimeSpan?>("Hours")
                                .HasColumnType("interval")
                                .HasColumnName("hours");

                            b1.Property<string>("Notes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("notes");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("reason");

                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uuid")
                                .HasColumnName("resource_id");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("type");

                            b1.HasKey("Id")
                                .HasName("pk_resource_adjustments");

                            b1.HasIndex("ResourceId", "DateFrom", "DateTo")
                                .HasDatabaseName("ix_resource_adjustments_resource_id_date_from_date_to");

                            b1.ToTable("resource_adjustments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ResourceId")
                                .HasConstraintName("fk_resource_adjustments_resources_resource_id");
                        });

                    b.OwnsMany("ResourcePulse.Domain.Calendars.WorkWindow", "WorkWindows", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("DayOfWeek")
                                .HasColumnType("integer")
                                .HasColumnName("day_of_week");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("end_time");

                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uuid")
                                .HasColumnName("resource_id");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("start_time");

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");

                            b1.HasKey("Id")
                                .HasName("pk_resource_work_windows");

                            b1.HasIndex("ResourceId", "ValidFrom", "ValidTo")
                                .HasDatabaseName("ix_resource_work_windows_resource_id_valid_from_valid_to");

                            b1.ToTable("resource_work_windows", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ResourceId")
                                .HasConstraintName("fk_resource_work_windows_resources_resource_id");
                        });

                    b.OwnsMany("ResourcePulse.Domain.Resources.ResourceSkill", "Skills", b1 =>
                        {
                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uuid")
                                .HasColumnName("resource_id");

                            b1.Property<Guid>("SkillId")
                                .HasColumnType("uuid")
                                .HasColumnName("skill_id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("created_by");

                            b1.Property<string>("Level")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("level");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("updated_by");

                            b1.HasKey("ResourceId", "SkillId")
                                .HasName("pk_resource_skills");

                            b1.HasIndex("SkillId")
                                .HasDatabaseName("ix_resource_skills_skill_id");

                            b1.ToTable("resource_skills", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ResourceId")
                                .HasConstraintName("fk_resource_skills_resources_resource_id");

                            b1.HasOne("ResourcePulse.Domain.Skills.Skill", null)
                                .WithMany()
                                .HasForeignKey("SkillId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("fk_resource_skills_skills_skill_id");
                        });

                    b.OwnsMany("ResourcePulse.Domain.Resources.ResourceTag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uuid")
                                .HasColumnName("resource_id");

                            b1.Property<Guid>("TagId")
                                .HasColumnType("uuid")
                                .HasColumnName("tag_id");

                            b1.HasKey("ResourceId", "TagId")
                                .HasName("pk_resource_tags");

                            b1.HasIndex("TagId")
                                .HasDatabaseName("ix_resource_tags_tag_id");

                            b1.ToTable("resource_tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ResourceId")
                                .HasConstraintName("fk_resource_tags_resources_resource_id");

                            b1.HasOne("ResourcePulse.Domain.Tags.Tag", null)
                                .WithMany()
                                .HasForeignKey("TagId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_resource_tags_tags_tag_id");
                        });

                    b.Navigation("Adjustments");

                    b.Navigation("Skills");

                    b.Navigation("Tags");

                    b.Navigation("WorkWindows");
                });
#pragma warning restore 612, 618
        }
    }
}
