// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResourcePulse.Persistence;

#nullable disable

namespace ResourcePulse.Persistence.Migrations
{
    [DbContext(typeof(ResourcePulseDbContext))]
    [Migration("20260517111436_AddCapacityModel")]
    partial class AddCapacityModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResourcePulse.Domain.Calendars.BusinessCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_business_calendars");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ix_business_calendars_is_default_unique")
                        .HasFilter("is_default = TRUE");

                    b.ToTable("business_calendars", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Calendars.CompanyClosure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_company_closures");

                    b.HasIndex("DateFrom", "DateTo")
                        .HasDatabaseName("ix_company_closures_date_from_date_to");

                    b.ToTable("company_closures", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Resources.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_calendar_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_resources");

                    b.HasIndex("BusinessCalendarId")
                        .HasDatabaseName("ix_resources_business_calendar_id");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Calendars.BusinessCalendar", b =>
                {
                    b.OwnsMany("ResourcePulse.Domain.Calendars.WorkWindow", "WorkWindows", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("BusinessCalendarId")
                                .HasColumnType("uuid")
                                .HasColumnName("business_calendar_id");

                            b1.Property<int>("DayOfWeek")
                                .HasColumnType("integer")
                                .HasColumnName("day_of_week");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("end_time");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("start_time");

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");

                            b1.HasKey("Id");

                            b1.HasIndex("BusinessCalendarId", "ValidFrom", "ValidTo")
                                .HasDatabaseName("ix_business_calendar_work_windows_business_calendar_id_valid_f");

                            b1.ToTable("business_calendar_work_windows", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BusinessCalendarId")
                                .HasConstraintName("fk_business_calendar_work_windows_business_calendars_business_");
                        });

                    b.Navigation("WorkWindows");
                });

            modelBuilder.Entity("ResourcePulse.Domain.Resources.Resource", b =>
                {
                    b.HasOne("ResourcePulse.Domain.Calendars.BusinessCalendar", null)
                        .WithMany()
                        .HasForeignKey("BusinessCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resources_business_calendars_business_calendar_id");

                    b.OwnsMany("ResourcePulse.Domain.Resources.IndividualAdjustment", "Adjustments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("DateFrom")
                                .HasColumnType("date")
                                .HasColumnName("date_from");

                            b1.Property<DateOnly>("DateTo")
                                .HasColumnType("date")
                                .HasColumnName("date_to");

                            b1.Property<TimeSpan?>("Hours")
                                .HasColumnType("interval")
                                .HasColumnName("hours");

                            b1.Property<string>("Notes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("notes");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("reason");

                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uuid")
                                .HasColumnName("resource_id");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("type");

                            b1.HasKey("Id")
                                .HasName("pk_resource_adjustments");

                            b1.HasIndex("ResourceId", "DateFrom", "DateTo")
                                .HasDatabaseName("ix_resource_adjustments_resource_id_date_from_date_to");

                            b1.ToTable("resource_adjustments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ResourceId")
                                .HasConstraintName("fk_resource_adjustments_resources_resource_id");
                        });

                    b.OwnsMany("ResourcePulse.Domain.Calendars.WorkWindow", "WorkWindows", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("DayOfWeek")
                                .HasColumnType("integer")
                                .HasColumnName("day_of_week");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("end_time");

                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uuid")
                                .HasColumnName("resource_id");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("start_time");

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");

                            b1.HasKey("Id")
                                .HasName("pk_resource_work_windows");

                            b1.HasIndex("ResourceId", "ValidFrom", "ValidTo")
                                .HasDatabaseName("ix_resource_work_windows_resource_id_valid_from_valid_to");

                            b1.ToTable("resource_work_windows", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ResourceId")
                                .HasConstraintName("fk_resource_work_windows_resources_resource_id");
                        });

                    b.Navigation("Adjustments");

                    b.Navigation("WorkWindows");
                });
#pragma warning restore 612, 618
        }
    }
}
