// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResourcePulse.Persistence;

#nullable disable

namespace ResourcePulse.Persistence.Migrations
{
    [DbContext(typeof(ResourcePulseDbContext))]
    [Migration("20260911080136_AddBoundaryAnchors")]
    partial class AddBoundaryAnchors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResourcePulse.Domain.Access.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("GrantedByUserSub")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("granted_by_user_sub");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserSub")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_sub");

                    b.HasKey("Id")
                        .HasName("pk_memberships");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_memberships_tenant_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ux_memberships_email");

                    b.HasIndex("TenantId", "UserSub")
                        .IsUnique()
                        .HasDatabaseName("ux_memberships_user_sub")
                        .HasFilter("user_sub IS NOT NULL");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Allocations.Allocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AllocationPercent")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("allocation_percent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DemandId")
                        .HasColumnType("uuid")
                        .HasColumnName("demand_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<Guid>("ProjectNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_node_id");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_allocations");

                    b.HasIndex("DemandId")
                        .HasDatabaseName("ix_allocations_demand_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_allocations_tenant_id");

                    b.HasIndex("ProjectNodeId", "PeriodStart", "PeriodEnd")
                        .HasDatabaseName("ix_allocations_project_node_id_period");

                    b.HasIndex("ResourceId", "PeriodStart", "PeriodEnd")
                        .HasDatabaseName("ix_allocations_resource_id_period");

                    b.ToTable("allocations", null, t =>
                        {
                            t.HasCheckConstraint("ck_allocations_end_anchor_shape", "(end_anchor_kind IN ('NodeStart', 'NodeEnd') AND end_anchor_node_id IS NOT NULL AND end_anchor_constraint_id IS NULL) OR (end_anchor_kind = 'External' AND end_anchor_constraint_id IS NOT NULL AND end_anchor_node_id IS NULL) OR (end_anchor_kind IN ('Pinned', 'ResourceAvailability') AND end_anchor_node_id IS NULL AND end_anchor_constraint_id IS NULL)");

                            t.HasCheckConstraint("ck_allocations_start_anchor_shape", "(start_anchor_kind IN ('NodeStart', 'NodeEnd') AND start_anchor_node_id IS NOT NULL AND start_anchor_constraint_id IS NULL) OR (start_anchor_kind = 'External' AND start_anchor_constraint_id IS NOT NULL AND start_anchor_node_id IS NULL) OR (start_anchor_kind IN ('Pinned', 'ResourceAvailability') AND start_anchor_node_id IS NULL AND start_anchor_constraint_id IS NULL)");
                        });
                });

            modelBuilder.Entity("ResourcePulse.Domain.Calendars.BusinessCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_business_calendars");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_business_calendars_tenant_id");

                    b.HasIndex("TenantId", "IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ix_business_calendars_is_default_unique")
                        .HasFilter("is_default = TRUE");

                    b.ToTable("business_calendars", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Calendars.CompanyClosure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_company_closures");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_company_closures_tenant_id");

                    b.HasIndex("DateFrom", "DateTo")
                        .HasDatabaseName("ix_company_closures_date_from_date_to");

                    b.ToTable("company_closures", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Configuration.BucketingDefaults", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("PrimaryGrain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("primary_grain");

                    b.Property<string>("SecondaryGrain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("secondary_grain");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_bucketing_defaults");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_bucketing_defaults_tenant");

                    b.ToTable("bucketing_defaults", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Configuration.CommitmentPolicyConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.Property<string>("_hardCommitLevels")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hard_commit_levels");

                    b.HasKey("Id")
                        .HasName("pk_commitment_policies");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_commitment_policies_tenant");

                    b.ToTable("commitment_policies", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Configuration.LoadBandConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_load_band_configurations");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_load_band_configurations_tenant");

                    b.ToTable("load_band_configurations", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Configuration.SignalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<int>("ResolvedRetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("resolved_retention_days");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_signal_policies");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_signal_policies_tenant");

                    b.ToTable("signal_policies", null, t =>
                        {
                            t.HasCheckConstraint("ck_signal_policies_retention_positive", "resolved_retention_days >= 1");
                        });
                });

            modelBuilder.Entity("ResourcePulse.Domain.Configuration.TimeFenceConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_time_fence_configurations");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_time_fence_configurations_tenant");

                    b.ToTable("time_fence_configurations", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Demands.Demand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DecideBy")
                        .HasColumnType("date")
                        .HasColumnName("decide_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OwnerResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_resource_id");

                    b.Property<Guid>("ProjectNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_node_id");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provenance");

                    b.Property<TimeSpan?>("RequiredHours")
                        .HasColumnType("interval")
                        .HasColumnName("required_hours");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_demands");

                    b.HasIndex("OwnerResourceId")
                        .HasDatabaseName("ix_demands_owner_resource_id");

                    b.HasIndex("ProjectNodeId")
                        .HasDatabaseName("ix_demands_project_node_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_demands_role_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_demands_tenant_id");

                    b.ToTable("demands", null, t =>
                        {
                            t.HasCheckConstraint("ck_demands_required_hours_positive", "required_hours IS NULL OR required_hours > INTERVAL '0'");
                        });
                });

            modelBuilder.Entity("ResourcePulse.Domain.Projects.ProjectNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActualEnd")
                        .HasColumnType("date")
                        .HasColumnName("actual_end");

                    b.Property<DateOnly?>("ActualStart")
                        .HasColumnType("date")
                        .HasColumnName("actual_start");

                    b.Property<DateOnly?>("BaselineEnd")
                        .HasColumnType("date")
                        .HasColumnName("baseline_end");

                    b.Property<DateOnly?>("BaselineStart")
                        .HasColumnType("date")
                        .HasColumnName("baseline_start");

                    b.Property<DateTimeOffset?>("BaselinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("baselined_at");

                    b.Property<string>("Client")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("client");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("CommitmentLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("commitment_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<TimeSpan?>("EstimatedWork")
                        .HasColumnType("interval")
                        .HasColumnName("estimated_work");

                    b.Property<Guid?>("LeadResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_resource_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("node_type");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("path");

                    b.Property<DateOnly?>("PlannedEnd")
                        .HasColumnType("date")
                        .HasColumnName("planned_end");

                    b.Property<DateOnly?>("PlannedStart")
                        .HasColumnType("date")
                        .HasColumnName("planned_start");

                    b.Property<string>("PlanningMode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("planning_mode");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_project_nodes");

                    b.HasIndex("LeadResourceId")
                        .HasDatabaseName("ix_project_nodes_lead_resource_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_project_nodes_parent_id");

                    b.HasIndex("Path")
                        .HasDatabaseName("ix_project_nodes_path");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Path"), new[] { "text_pattern_ops" });

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_project_nodes_tenant_id");

                    b.HasIndex("NodeType", "Status")
                        .HasDatabaseName("ix_project_nodes_node_type_status");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_project_nodes_root_code")
                        .HasFilter("parent_id IS NULL AND code IS NOT NULL");

                    b.HasIndex("TenantId", "ParentId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_project_nodes_parent_code")
                        .HasFilter("parent_id IS NOT NULL AND code IS NOT NULL");

                    b.ToTable("project_nodes", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Resources.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_calendar_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserSub")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_sub");

                    b.HasKey("Id")
                        .HasName("pk_resources");

                    b.HasIndex("BusinessCalendarId")
                        .HasDatabaseName("ix_resources_business_calendar_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_resources_role_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_resources_team_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_resources_tenant_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ux_resources_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("TenantId", "UserSub")
                        .IsUnique()
                        .HasDatabaseName("ux_resources_user_sub")
                        .HasFilter("user_sub IS NOT NULL");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_roles_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Signals.PlanSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DeadlineAt")
                        .HasColumnType("date")
                        .HasColumnName("deadline_at");

                    b.Property<string>("Detection")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("detection");

                    b.Property<DateTimeOffset>("FirstDetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_detected_at");

                    b.Property<bool>("HardCommitted")
                        .HasColumnType("boolean")
                        .HasColumnName("hard_committed");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<int>("LastChange")
                        .HasColumnType("integer")
                        .HasColumnName("last_change");

                    b.Property<DateTimeOffset?>("LastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed_at");

                    b.Property<DateTimeOffset>("LastObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at");

                    b.Property<decimal>("Magnitude")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("magnitude");

                    b.Property<decimal?>("PreviousMagnitude")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("previous_magnitude");

                    b.Property<string>("PreviousZone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("previous_zone");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.Property<string>("Zone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zone");

                    b.PrimitiveCollection<List<Guid>>("_memberSubjectIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("member_subject_ids");

                    b.PrimitiveCollection<List<Guid>>("_touchedRootProjectIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("touched_root_project_ids");

                    b.HasKey("Id")
                        .HasName("pk_plan_signals");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_plan_signals_tenant_id");

                    b.HasIndex("_touchedRootProjectIds")
                        .HasDatabaseName("ix_plan_signals_touched_roots");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("_touchedRootProjectIds"), "gin");

                    b.HasIndex("TenantId", "Detection")
                        .HasDatabaseName("ix_plan_signals_detection");

                    b.HasIndex("TenantId", "LastChangedAt")
                        .HasDatabaseName("ix_plan_signals_last_changed_at");

                    b.ToTable("plan_signals", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Signals.SignalSweepState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<int>("LastLiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("last_live_count");

                    b.Property<DateTimeOffset?>("LastSweptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_swept_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_signal_sweep_states");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_signal_sweep_states_tenant");

                    b.ToTable("signal_sweep_states", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Signals.SignalVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("LastVisitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visited_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserSub")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_sub");

                    b.HasKey("Id")
                        .HasName("pk_signal_visits");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_signal_visits_tenant_id");

                    b.HasIndex("TenantId", "UserSub")
                        .IsUnique()
                        .HasDatabaseName("ux_signal_visits_user_sub");

                    b.ToTable("signal_visits", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Skills.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_skills_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_skills_name");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tags_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_teams_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_teams_name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("ResourcePulse.Domain.Allocations.Allocation", b =>
                {
                    b.HasOne("ResourcePulse.Domain.Demands.Demand", null)
                        .WithMany()
                        .HasForeignKey("DemandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_allocations_demands_demand_id");

                    b.HasOne("ResourcePulse.Domain.Projects.ProjectNode", null)
                        .WithMany()
                        .HasForeignKey("ProjectNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_allocations_project_nodes_project_node_id");

                    b.HasOne("ResourcePulse.Domain.Resources.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_allocations_resources_resource_id");

                    b.OwnsOne("ResourcePulse.Domain.Allocations.BoundaryAnchor", "EndAnchor", b1 =>
                        {
                            b1.Property<Guid>("AllocationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("ConstraintId")
                                .HasColumnType("uuid")
                                .HasColumnName("end_anchor_constraint_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasDefaultValue("Pinned")
                                .HasColumnName("end_anchor_kind");

                            b1.Property<Guid?>("NodeId")
                                .HasColumnType("uuid")
                                .HasColumnName("end_anchor_node_id");

                            b1.HasKey("AllocationId");

                            b1.HasIndex("NodeId")
                                .HasDatabaseName("ix_allocations_end_anchor_node_id");

                            b1.ToTable("allocations");

                            b1.WithOwner()
                                .HasForeignKey("AllocationId")
                                .HasConstraintName("fk_allocations_allocations_id");

                            b1.HasOne("ResourcePulse.Domain.Projects.ProjectNode", null)
                                .WithMany()
                                .HasForeignKey("NodeId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .HasConstraintName("fk_allocations_project_nodes_end_anchor_node_id");
                        });

                    b.OwnsOne("ResourcePulse.Domain.Allocations.BoundaryAnchor", "StartAnchor", b1 =>
                        {
                            b1.Property<Guid>("AllocationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("ConstraintId")
                                .HasColumnType("uuid")
                                .HasColumnName("start_anchor_constraint_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasDefaultValue("Pinned")
                                .HasColumnName("start_anchor_kind");

                            b1.Property<Guid?>("NodeId")
                                .HasColumnType("uuid")
                                .HasColumnName("start_anchor_node_id");

                            b1.HasKey("AllocationId");

                            b1.HasIndex("NodeId")
                                .HasDatabaseName("ix_allocations_start_anchor_node_id");

                            b1.ToTable("allocations");

                            b1.WithOwner()
                                .HasForeignKey("AllocationId")
                                .HasConstraintName("fk_allocations_allocations_id");

                            b1.HasOne("ResourcePulse.Domain.Projects.ProjectNode", null)
                                .WithMany()
                                .HasForeignKey("NodeId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .HasConstraintName("fk_allocations_project_nodes_start_anchor_node_id");
                        });

                    b.Navigation("EndAnchor")
                        .IsRequired();

                    b.Navigation("StartAnchor")
                        .IsRequired();
                });

            modelBuilder.Entity("ResourcePulse.Domain.Calendars.BusinessCalendar", b =>
                {
                    b.OwnsMany("ResourcePulse.Domain.Calendars.WorkWindow", "WorkWindows", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("BusinessCalendarId")
                                .HasColumnType("uuid")
                                .HasColumnName("business_calendar_id");

                            b1.Property<int>("DayOfWeek")
                                .HasColumnType("integer")
                                .HasColumnName("day_of_week");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("end_time");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("start_time");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");

                            b1.HasKey("Id");

                            b1.HasIndex("TenantId")
                                .HasDatabaseName("ix_business_calendar_work_windows_tenant_id");

                            b1.HasIndex("BusinessCalendarId", "ValidFrom", "ValidTo")
                                .HasDatabaseName("ix_business_calendar_work_windows_business_calendar_id_valid_f");

                            b1.ToTable("business_calendar_work_windows", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BusinessCalendarId")
                                .HasConstraintName("fk_business_calendar_work_windows_business_calendars_business_");
                        });

                    b.Navigation("WorkWindows");
                });

            modelBuilder.Entity("ResourcePulse.Domain.Configuration.LoadBandConfiguration", b =>
                {
                    b.OwnsMany("ResourcePulse.Domain.Configuration.LoadBand", "Bands", b1 =>
                        {
                            b1.Property<Guid>("LoadBandConfigurationId")
                                .HasColumnType("uuid")
                                .HasColumnName("load_band_configuration_id");

                            b1.Property<decimal>("LowerBound")
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("lower_bound");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.HasKey("LoadBandConfigurationId", "LowerBound")
                                .HasName("pk_load_bands");

                            b1.HasIndex("TenantId")
                                .HasDatabaseName("ix_load_bands_tenant_id");

                            b1.ToTable("load_bands", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LoadBandConfigurationId")
                                .HasConstraintName("fk_load_bands_load_band_configurations_load_band_configuration");
                        });

                    b.Navigation("Bands");
                });

            modelBuilder.Entity("ResourcePulse.Domain.Configuration.SignalPolicy", b =>
                {
                    b.OwnsOne("ResourcePulse.Domain.Configuration.Duration", "DecisionLeadTime", b1 =>
                        {
                            b1.Property<Guid>("SignalPolicyId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("decision_lead_time_unit");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("decision_lead_time_value");

                            b1.HasKey("SignalPolicyId");

                            b1.ToTable("signal_policies");

                            b1.WithOwner()
                                .HasForeignKey("SignalPolicyId")
                                .HasConstraintName("fk_signal_policies_signal_policies_id");
                        });

                    b.Navigation("DecisionLeadTime")
                        .IsRequired();
                });

            modelBuilder.Entity("ResourcePulse.Domain.Configuration.TimeFenceConfiguration", b =>
                {
                    b.OwnsOne("ResourcePulse.Domain.Configuration.Duration", "FrozenHorizon", b1 =>
                        {
                            b1.Property<Guid>("TimeFenceConfigurationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("frozen_horizon_unit");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("frozen_horizon_value");

                            b1.HasKey("TimeFenceConfigurationId");

                            b1.ToTable("time_fence_configurations");

                            b1.WithOwner()
                                .HasForeignKey("TimeFenceConfigurationId")
                                .HasConstraintName("fk_time_fence_configurations_time_fence_configurations_id");
                        });

                    b.OwnsOne("ResourcePulse.Domain.Configuration.Duration", "SlushyHorizon", b1 =>
                        {
                            b1.Property<Guid>("TimeFenceConfigurationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("slushy_horizon_unit");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("slushy_horizon_value");

                            b1.HasKey("TimeFenceConfigurationId");

                            b1.ToTable("time_fence_configurations");

                            b1.WithOwner()
                                .HasForeignKey("TimeFenceConfigurationId")
                                .HasConstraintName("fk_time_fence_configurations_time_fence_configurations_id");
                        });

                    b.Navigation("FrozenHorizon")
                        .IsRequired();

                    b.Navigation("SlushyHorizon")
                        .IsRequired();
                });

            modelBuilder.Entity("ResourcePulse.Domain.Demands.Demand", b =>
                {
                    b.HasOne("ResourcePulse.Domain.Resources.Resource", null)
                        .WithMany()
                        .HasForeignKey("OwnerResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_demands_resources_owner_resource_id");

                    b.HasOne("ResourcePulse.Domain.Projects.ProjectNode", null)
                        .WithMany()
                        .HasForeignKey("ProjectNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_demands_project_nodes_project_node_id");

                    b.HasOne("ResourcePulse.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_demands_roles_role_id");
                });

            modelBuilder.Entity("ResourcePulse.Domain.Projects.ProjectNode", b =>
                {
                    b.HasOne("ResourcePulse.Domain.Resources.Resource", null)
                        .WithMany()
                        .HasForeignKey("LeadResourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_project_nodes_resources_lead_resource_id");

                    b.HasOne("ResourcePulse.Domain.Projects.ProjectNode", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_project_nodes_project_nodes_parent_id");

                    b.OwnsMany("ResourcePulse.Domain.Projects.ProjectNodeTag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("ProjectNodeId")
                                .HasColumnType("uuid")
                                .HasColumnName("project_node_id");

                            b1.Property<Guid>("TagId")
                                .HasColumnType("uuid")
                                .HasColumnName("tag_id");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.HasKey("ProjectNodeId", "TagId")
                                .HasName("pk_project_node_tags");

                            b1.HasIndex("TagId")
                                .HasDatabaseName("ix_project_node_tags_tag_id");

                            b1.HasIndex("TenantId")
                                .HasDatabaseName("ix_project_node_tags_tenant_id");

                            b1.ToTable("project_node_tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProjectNodeId")
                                .HasConstraintName("fk_project_node_tags_project_nodes_project_node_id");

                            b1.HasOne("ResourcePulse.Domain.Tags.Tag", null)
                                .WithMany()
                                .HasForeignKey("TagId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_project_node_tags_tags_tag_id");
                        });

                    b.OwnsMany("ResourcePulse.Domain.Projects.ProjectSkillRequirement", "SkillRequirements", b1 =>
                        {
                            b1.Property<Guid>("ProjectNodeId")
                                .HasColumnType("uuid")
                                .HasColumnName("project_node_id");

                            b1.Property<Guid>("SkillId")
                                .HasColumnType("uuid")
                                .HasColumnName("skill_id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("created_by");

                            b1.Property<string>("MinLevel")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("min_level");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("updated_by");

                            b1.HasKey("ProjectNodeId", "SkillId")
                                .HasName("pk_project_skill_requirements");

                            b1.HasIndex("SkillId")
                                .HasDatabaseName("ix_project_skill_requirements_skill_id");

                            b1.HasIndex("TenantId")
                                .HasDatabaseName("ix_project_skill_requirements_tenant_id");

                            b1.ToTable("project_skill_requirements", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProjectNodeId")
                                .HasConstraintName("fk_project_skill_requirements_project_nodes_project_node_id");

                            b1.HasOne("ResourcePulse.Domain.Skills.Skill", null)
                                .WithMany()
                                .HasForeignKey("SkillId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("fk_project_skill_requirements_skills_skill_id");
                        });

                    b.Navigation("SkillRequirements");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ResourcePulse.Domain.Resources.Resource", b =>
                {
                    b.HasOne("ResourcePulse.Domain.Calendars.BusinessCalendar", null)
                        .WithMany()
                        .HasForeignKey("BusinessCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resources_business_calendars_business_calendar_id");

                    b.HasOne("ResourcePulse.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_resources_roles_role_id");

                    b.HasOne("ResourcePulse.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_resources_teams_team_id");

                    b.OwnsMany("ResourcePulse.Domain.Resources.IndividualAdjustment", "Adjustments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("DateFrom")
                                .HasColumnType("date")
                                .HasColumnName("date_from");

                            b1.Property<DateOnly>("DateTo")
                                .HasColumnType("date")
                                .HasColumnName("date_to");

                            b1.Property<TimeSpan?>("Hours")
                                .HasColumnType("interval")
                                .HasColumnName("hours");

                            b1.Property<string>("Notes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("notes");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("reason");

                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uuid")
                                .HasColumnName("resource_id");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("type");

                            b1.HasKey("Id")
                                .HasName("pk_resource_adjustments");

                            b1.HasIndex("TenantId")
                                .HasDatabaseName("ix_resource_adjustments_tenant_id");

                            b1.HasIndex("ResourceId", "DateFrom", "DateTo")
                                .HasDatabaseName("ix_resource_adjustments_resource_id_date_from_date_to");

                            b1.ToTable("resource_adjustments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ResourceId")
                                .HasConstraintName("fk_resource_adjustments_resources_resource_id");
                        });

                    b.OwnsMany("ResourcePulse.Domain.Calendars.WorkWindow", "WorkWindows", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("DayOfWeek")
                                .HasColumnType("integer")
                                .HasColumnName("day_of_week");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("end_time");

                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uuid")
                                .HasColumnName("resource_id");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("start_time");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");

                            b1.HasKey("Id")
                                .HasName("pk_resource_work_windows");

                            b1.HasIndex("TenantId")
                                .HasDatabaseName("ix_resource_work_windows_tenant_id");

                            b1.HasIndex("ResourceId", "ValidFrom", "ValidTo")
                                .HasDatabaseName("ix_resource_work_windows_resource_id_valid_from_valid_to");

                            b1.ToTable("resource_work_windows", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ResourceId")
                                .HasConstraintName("fk_resource_work_windows_resources_resource_id");
                        });

                    b.OwnsMany("ResourcePulse.Domain.Resources.ResourceSkill", "Skills", b1 =>
                        {
                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uuid")
                                .HasColumnName("resource_id");

                            b1.Property<Guid>("SkillId")
                                .HasColumnType("uuid")
                                .HasColumnName("skill_id");

                            b1.Property<string>("ApprovalStatus")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("approval_status");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("created_by");

                            b1.Property<string>("Level")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("level");

                            b1.Property<DateTime?>("ReviewedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("reviewed_at");

                            b1.Property<Guid?>("ReviewedByResourceId")
                                .HasColumnType("uuid")
                                .HasColumnName("reviewed_by_resource_id");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("updated_by");

                            b1.HasKey("ResourceId", "SkillId")
                                .HasName("pk_resource_skills");

                            b1.HasIndex("ReviewedByResourceId")
                                .HasDatabaseName("ix_resource_skills_reviewed_by_resource_id");

                            b1.HasIndex("SkillId")
                                .HasDatabaseName("ix_resource_skills_skill_id");

                            b1.HasIndex("TenantId")
                                .HasDatabaseName("ix_resource_skills_tenant_id");

                            b1.ToTable("resource_skills", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ResourceId")
                                .HasConstraintName("fk_resource_skills_resources_resource_id");

                            b1.HasOne("ResourcePulse.Domain.Resources.Resource", null)
                                .WithMany()
                                .HasForeignKey("ReviewedByResourceId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .HasConstraintName("fk_resource_skills_resources_reviewed_by_resource_id");

                            b1.HasOne("ResourcePulse.Domain.Skills.Skill", null)
                                .WithMany()
                                .HasForeignKey("SkillId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("fk_resource_skills_skills_skill_id");
                        });

                    b.OwnsMany("ResourcePulse.Domain.Resources.ResourceTag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uuid")
                                .HasColumnName("resource_id");

                            b1.Property<Guid>("TagId")
                                .HasColumnType("uuid")
                                .HasColumnName("tag_id");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.HasKey("ResourceId", "TagId")
                                .HasName("pk_resource_tags");

                            b1.HasIndex("TagId")
                                .HasDatabaseName("ix_resource_tags_tag_id");

                            b1.HasIndex("TenantId")
                                .HasDatabaseName("ix_resource_tags_tenant_id");

                            b1.ToTable("resource_tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ResourceId")
                                .HasConstraintName("fk_resource_tags_resources_resource_id");

                            b1.HasOne("ResourcePulse.Domain.Tags.Tag", null)
                                .WithMany()
                                .HasForeignKey("TagId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_resource_tags_tags_tag_id");
                        });

                    b.Navigation("Adjustments");

                    b.Navigation("Skills");

                    b.Navigation("Tags");

                    b.Navigation("WorkWindows");
                });

            modelBuilder.Entity("ResourcePulse.Domain.Signals.PlanSignal", b =>
                {
                    b.OwnsMany("ResourcePulse.Domain.Signals.SignalAcknowledgement", "Acknowledgements", b1 =>
                        {
                            b1.Property<Guid>("PlanSignalId")
                                .HasColumnType("uuid")
                                .HasColumnName("plan_signal_id");

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer")
                                .HasColumnName("sequence");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("action");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("at");

                            b1.Property<string>("By")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("by");

                            b1.Property<string>("Reason")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("reason");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.HasKey("PlanSignalId", "Sequence")
                                .HasName("pk_signal_acknowledgements");

                            b1.HasIndex("TenantId")
                                .HasDatabaseName("ix_signal_acknowledgements_tenant_id");

                            b1.ToTable("signal_acknowledgements", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PlanSignalId")
                                .HasConstraintName("fk_signal_acknowledgements_plan_signals_plan_signal_id");
                        });

                    b.Navigation("Acknowledgements");
                });
#pragma warning restore 612, 618
        }
    }
}
